<a href="https://colab.research.google.com/github/NIKHIL-SEKHAR/AI_ML_COURSE_ICTAK_NIKHIL/blob/main/Assignment_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY PROBLEMS

In [1]:
import numpy as np



1.Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.

In [3]:
array = np.arange(1,21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
array=np.reshape(array,(4,5))
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])



2. Create an array of 10 zeros and replace the 5th element with 100.


In [6]:
array= np.zeros(10)
array[4]=100
array

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])



3.Create a NumPy array of even numbers between 2 and 40."


In [7]:
array = np.arange(2,41,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])



4. Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.


In [8]:
random_integers = np.random.randint(1,101,15)
random_integers

array([38, 32, 87, 79,  3, 38,  8, 93, 96, 15, 50, 77, 30, 60, 58])

In [10]:
#MINIMUM VALUE IN THE ARRAY
random_integers.min()

np.int64(3)

In [12]:
#MAXIMUM VALUE IN THE ARRAY
random_integers.max()

np.int64(96)

In [14]:
#MEAN OF THE ARRAY
random_integers.mean()

np.float64(50.93333333333333)

In [16]:
#STANDARD DEVIATION OF THE ARRAY
random_integers.std()

np.float64(29.737667845493345)



5.Given two arrays of sales and costs, calculate profit and profit percentage arrays.


In [17]:
sales = np.array([1000, 2000, 3000, 4000, 5000])
costs = np.array([500, 1000, 1500, 2000, 2500])

profit = sales - costs
profit

array([ 500, 1000, 1500, 2000, 2500])

In [20]:
profit_percentage = (profit / sales) * 100
PRO_PER = profit_percentage.round(2)
PRO_PER

array([50., 50., 50., 50., 50.])



6. Create a 6×6 random matrix and compute row sums, column sums, and total sum.



In [22]:
np.random.seed(10)

In [24]:
Matrix = np.random.randint(1,100, size=(6,6))
Matrix


array([[58, 37, 28, 19, 94, 78],
       [23, 24, 95, 12, 29, 75],
       [89, 10, 16, 19, 81, 72],
       [89, 12, 18, 47,  8, 76],
       [29, 34, 85, 97, 89, 45],
       [ 6,  5, 72, 89, 89, 51]])

In [26]:
print("Row sum :" ,Matrix.sum(axis=1))

Row sum : [314 258 287 250 379 312]


In [28]:
print("Column sums: ", Matrix.sum(axis=0))

Column sums:  [294 122 314 283 390 397]


In [29]:
print(" total sum:" ,Matrix.sum())

 total sum: 1800




7.Given stock prices, compute daily returns using vectorized NumPy operations.


In [31]:
prices = np.array([100, 102, 98, 105, 107, 103, 110])
daily_returns = (prices[1:] - prices[:-1]) / prices[:-1]
print("Stock Prices:", prices)
print("Daily Returns:", daily_returns.round(4))

Stock Prices: [100 102  98 105 107 103 110]
Daily Returns: [ 0.02   -0.0392  0.0714  0.019  -0.0374  0.068 ]




8.Convert an array of annual interest rates into monthly rates using vectorization.


In [32]:
annual_rates = np.array([0.06, 0.08, 0.12, 0.05])
monthly_rates = annual_rates / 12
print("Annual Interest Rates:", annual_rates)
print("Monthly Interest Rates:", monthly_rates.round(4))

Annual Interest Rates: [0.06 0.08 0.12 0.05]
Monthly Interest Rates: [0.005  0.0067 0.01   0.0042]




9.Normalize a given array of portfolio weights so that the sum becomes 1.


In [33]:
weights = np.array([30, 25, 20, 15, 10])
normalized_weights = weights / weights.sum()
print("Original weights:", weights)
print("Normalized (sum=1):", normalized_weights.round(4))

Original weights: [30 25 20 15 10]
Normalized (sum=1): [0.3  0.25 0.2  0.15 0.1 ]




10.  Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]


Create series and stats.

In [35]:
import pandas as pd
data = [1200, 1500, 1800, 2000, 2200]
s = pd.Series(data, index=['Jan', 'Feb', 'Mar', 'Apr', 'May'])
print("Series:\n", s)
print("Mean:", s.mean())
print("Max:", s.max())
print("Index of max:", s.idxmax())  # or s.index[s.argmax()]

Series:
 Jan    1200
Feb    1500
Mar    1800
Apr    2000
May    2200
dtype: int64
Mean: 1740.0
Max: 2200
Index of max: May




11. Student Marks DataFrame


In [38]:
df_students = pd.DataFrame({
    'Name': ['NIKHIL SEKHAR', 'SRUTHI', 'LAKSHMI', 'ANJITHA'],
    'English': [82, 81, 90, 75],
    'Biology': [80, 93, 79, 86],
    'Maths': [93, 88, 84, 90]
})

print("Full DataFrame:\n", df_students)
print("English column:\n", df_students['English'])
print("First 2 rows:\n", df_students.head(2))
print("Shape:", df_students.shape)

Full DataFrame:
             Name  English  Biology  Maths
0  NIKHIL SEKHAR       82       80     93
1         SRUTHI       81       93     88
2        LAKSHMI       90       79     84
3        ANJITHA       75       86     90
English column:
 0    82
1    81
2    90
3    75
Name: English, dtype: int64
First 2 rows:
             Name  English  Biology  Maths
0  NIKHIL SEKHAR       82       80     93
1         SRUTHI       81       93     88
Shape: (4, 4)




12. Account Balance Filtering


In [42]:
df = pd.DataFrame({
    "Account": [2001, 2002, 2003, 2004],
    "Balance": [6000, 14000, 8000, 13000]
})
print("Original DF:\n", df)
print("Balance > 7000:\n", df[df['Balance'] > 7000])
print("Balance between 7000 and 14000:\n",
      df[df['Balance'].between(7000, 13000)])

Original DF:
    Account  Balance
0     2001     6000
1     2002    14000
2     2003     8000
3     2004    13000
Balance > 7000:
    Account  Balance
1     2002    14000
2     2003     8000
3     2004    13000
Balance between 7000 and 14000:
    Account  Balance
2     2003     8000
3     2004    13000
